from __future__ import annotations

import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from dotenv import load_dotenv

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib

CONFIG_DIR = Path.home() / ".aisk"
CONFIG_FILE = CONFIG_DIR / "conf.toml"
ENV_FILE = CONFIG_DIR / ".env"

DEFAULT_ENDPOINT = "https://openrouter.ai/api/v1/chat/completions"
_ANSI_SGR_RE = re.compile(r"\033\[[0-9;]*m")

# Single source of truth for the default model aliases, grouped by provider.
# Both DEFAULT_ALIASES (the dict) and DEFAULT_CONF_TOML (the template written by
# `aisk init`) are derived from this — no manual syncing between two lists.
_ALIAS_GROUPS: list[tuple[str, list[tuple[str, str]]]] = [
    ("Google Gemini", [
        ("gep", "google/gemini-3.1-pro-preview"),
        ("gef", "google/gemini-3.5-flash"),
        ("gel", "google/gemini-3.1-flash-lite-preview"),
        ("ge25lite", "google/gemini-2.5-flash-lite"),
    ]),
    ("OpenAI", [
        ("gpt", "openai/gpt-5.5"),
        ("gptpro", "openai/gpt-5.5-pro"),
        ("gptmini", "openai/gpt-5.4-mini"),
        ("gptnano", "openai/gpt-5.4-nano"),
    ]),
    ("Anthropic", [
        ("clo", "anthropic/claude-opus-4.8"),
        ("cls", "anthropic/claude-sonnet-4.6"),
        ("clh", "anthropic/claude-haiku-4.5"),
    ]),
    ("DeepSeek", [
        ("dsf", "deepseek/deepseek-v4-flash"),
        ("dsp", "deepseek/deepseek-v4-pro"),
    ]),
    ("Qwen", [
        ("qwen", "qwen/qwen3.7-max"),
    ]),
    ("Perplexity", [
        ("s", "perplexity/sonar"),
        ("sps", "perplexity/sonar-pro-search"),
    ]),
    ("Other", [
        ("mm", "minimax/minimax-m2.7"),
        ("glm", "z-ai/glm-5.1"),
        ("kimi", "moonshotai/kimi-k2.6"),
        ("mistral", "mistralai/mistral-large-2512"),
        ("lscout", "meta-llama/llama-4-scout:groq"),
        ("lmav", "meta-llama/llama-4-maverick:groq"),
    ]),
]

DEFAULT_ALIASES: dict[str, str] = {
    alias: model for _, items in _ALIAS_GROUPS for alias, model in items
}

DEFAULT_SHORTCUTS: dict[str, str] = {
    "ds": "dsf",
    "news": "sps",
}

ALIAS_RENAMES: dict[str, str] = {
    "ge31pro": "gep",
    "ge35flash": "gef",
    "ge31lite": "gel",
    "gpt55": "gpt",
    "gpt55pro": "gptpro",
    "gpt54mini": "gptmini",
    "gpt54nano": "gptnano",
    "clo48": "clo",
    "cls46": "cls",
    "clh45": "clh",
    "dsv4f": "dsf",
    "dsv4p": "dsp",
    "qwen37": "qwen",
    "m27": "mm",
    "glm51": "glm",
    "kimi26": "kimi",
    "l4scout": "lscout",
    "l4mav": "lmav",
}

# Alias keys ever shipped as defaults and since removed/renamed. Used by
# `aisk sync` to drop stale defaults from a user's conf.toml while keeping
# genuinely custom aliases. Invariant: disjoint from DEFAULT_ALIASES.
RETIRED_ALIASES: frozenset[str] = frozenset({
    # M22 (apr 2026)
    "clo46", "gpt54", "dsv32", "dsr1", "glm5", "m25", "qwen35p", "qwen35",
    # M24 (jun 2026)
    "clo47", "qwen36p", "ge25flash",
    # M28 (jun 2026)
    "gpt5mini", "gpt5nano", "o4m",
    # M37 (jun 2026): aliases now avoid model-version numbers by default.
    *ALIAS_RENAMES,
    # stale before M22
    "gpt5", "gpt51", "gpt52", "ge3flash", "k25",
})

# Commented-out shortcut examples (name, alias) shown in the generated conf.toml.
_SHORTCUT_EXAMPLES = [("gp", "gptpro"), ("cl", "cls"), ("ge", "gef")]


def _render_conf(
    endpoint: str,
    custom_aliases: dict[str, str] | None = None,
    shortcuts: dict[str, str] | None = None,
    *,
    shortcut_examples: bool = False,
) -> str:
    """Render a conf.toml: default alias groups (+ optional custom group),
    the given endpoint, and the given shortcuts."""
    lines = ["[api]", f'endpoint = "{endpoint}"', "", "[aliases]"]
    for i, (label, items) in enumerate(_ALIAS_GROUPS):
        if i > 0:
            lines.append("")
        lines.append(f"# {label}")
        for alias, model in items:
            lines.append(f'{alias} = "{model}"')
    if custom_aliases:
        lines.append("")
        lines.append("# Custom")
        for alias in sorted(custom_aliases):
            lines.append(f'{alias} = "{custom_aliases[alias]}"')

    lines += [
        "",
        "[shortcuts]",
        '# Shell functions generated by `eval "$(aisk completions bash)"`',
        '# Each key becomes a shell function: ds() { aisk dsf "$@"; }',
    ]
    for name, alias in (DEFAULT_SHORTCUTS if shortcuts is None else shortcuts).items():
        lines.append(f'{name} = "{alias}"')
    if shortcut_examples:
        for name, alias in _SHORTCUT_EXAMPLES:
            lines.append(f'# {name} = "{alias}"')

    return "\n".join(lines) + "\n"


def _render_default_conf(endpoint: str = DEFAULT_ENDPOINT) -> str:
    """Render the default conf.toml from _ALIAS_GROUPS + DEFAULT_SHORTCUTS."""
    return _render_conf(endpoint, shortcuts=DEFAULT_SHORTCUTS, shortcut_examples=True)


DEFAULT_CONF_TOML = _render_default_conf()

DEFAULT_ENV = """\
AISK_API_KEY=
"""


@dataclass
class Config:
    endpoint: str = DEFAULT_ENDPOINT
    api_key: str = ""
    aliases: dict[str, str] = field(default_factory=lambda: dict(DEFAULT_ALIASES))
    shortcuts: dict[str, str] = field(default_factory=lambda: dict(DEFAULT_SHORTCUTS))
    prompt_cache: bool = True


def _env_bool(name: str, default: bool) -> bool:
    """Read a boolean env var. '0', 'false', 'no', 'off' (any case) → False."""
    val = os.environ.get(name)
    if val is None:
        return default
    return val.strip().lower() not in ("0", "false", "no", "off", "")


def load_config() -> Config:
    """Load config from ~/.aisk/conf.toml and ~/.aisk/.env."""
    # Load .env first so AISK_API_KEY is available
    if ENV_FILE.exists():
        load_dotenv(ENV_FILE)

    cfg = Config()

    if CONFIG_FILE.exists():
        with open(CONFIG_FILE, "rb") as f:
            data = tomllib.load(f)
        api = data.get("api", {})
        if "endpoint" in api:
            cfg.endpoint = api["endpoint"]
        aliases = data.get("aliases", {})
        if aliases:
            cfg.aliases.update(aliases)
        shortcuts = data.get("shortcuts", {})
        if shortcuts:
            cfg.shortcuts.update(shortcuts)

    # An explicit endpoint in the environment (or ~/.aisk/.env, loaded above)
    # wins over conf.toml — lets you point aisk at any OpenAI-compatible
    # endpoint without editing files.
    env_endpoint = os.environ.get("AISK_ENDPOINT")
    if env_endpoint:
        cfg.endpoint = env_endpoint

    cfg.api_key = os.environ.get("AISK_API_KEY", "")
    cfg.prompt_cache = _env_bool("AISK_PROMPT_CACHE", True)
    return cfg


class ConfigError(Exception):
    """Raised when config cannot be loaded and auto-init is not possible."""


def ensure_config() -> Config:
    """Load config, auto-launching the setup wizard if needed.

    - If config/key is missing and stdin is a TTY → run interactive_init(), then reload.
    - If config/key is missing and stdin is NOT a TTY → raise ConfigError.
    - Otherwise → return the loaded Config.
    """
    cfg = load_config()
    if cfg.api_key:
        return cfg

    # Config or API key is missing — try auto-init
    if sys.stdin.isatty():
        print("\n  First run detected — launching setup wizard...\n")
        interactive_init(auto=True)
        # Reload after wizard
        cfg = load_config()
        if cfg.api_key:
            return cfg

    raise ConfigError("AISK_API_KEY not set. Run 'aisk init' and edit ~/.aisk/.env")


def init_config() -> list[str]:
    """Create ~/.aisk/ with default files (non-interactive). Returns list of actions taken."""
    actions: list[str] = []
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    if CONFIG_FILE.exists():
        actions.append(f"Skipped {CONFIG_FILE} (already exists)")
    else:
        # Honor AISK_ENDPOINT when set (e.g. `curl ... | AISK_ENDPOINT=... bash`)
        # so a custom endpoint is persisted into the generated conf.toml.
        _write_conf(os.environ.get("AISK_ENDPOINT", DEFAULT_ENDPOINT))
        actions.append(f"Created {CONFIG_FILE}")

    if ENV_FILE.exists():
        actions.append(f"Skipped {ENV_FILE} (already exists)")
    else:
        _write_env("")
        actions.append(f"Created {ENV_FILE}")

    return actions


def sync_aliases() -> dict[str, list[str]]:
    """Rewrite the [aliases] of conf.toml to the current defaults.

    Preserves [api] (endpoint), [shortcuts] and any genuinely custom aliases
    (keys neither in the current defaults nor previously shipped as defaults).
    Stale ex-defaults are dropped. Returns a summary with keys
    ``added``/``updated``/``removed``/``kept`` (sorted alias lists).

    If conf.toml does not exist yet, this is equivalent to `aisk init`.
    """
    if not CONFIG_FILE.exists():
        init_config()
        return {"added": sorted(DEFAULT_ALIASES), "updated": [], "removed": [], "kept": []}

    with open(CONFIG_FILE, "rb") as f:
        data = tomllib.load(f)
    endpoint = data.get("api", {}).get("endpoint", DEFAULT_ENDPOINT)
    existing = data.get("aliases", {})
    shortcuts = data.get("shortcuts", {})

    managed = set(DEFAULT_ALIASES) | RETIRED_ALIASES
    custom = {k: v for k, v in existing.items() if k not in managed}

    summary = {
        "added": sorted(k for k in DEFAULT_ALIASES if k not in existing),
        "updated": sorted(
            k for k, v in DEFAULT_ALIASES.items() if k in existing and existing[k] != v
        ),
        "removed": sorted(k for k in existing if k in RETIRED_ALIASES),
        "kept": sorted(custom),
    }

    CONFIG_FILE.write_text(_render_conf(endpoint, custom, shortcuts))
    return summary


def _mask_key(key: str) -> str:
    """Mask an API key for display, showing first 6 and last 4 chars."""
    if len(key) <= 10:
        return "****"
    return f"{key[:6]}...{key[-4:]}"


def _read_existing_key() -> str:
    """Read the current AISK_API_KEY from the .env file, if any."""
    if not ENV_FILE.exists():
        return ""
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if line.startswith("AISK_API_KEY=") and not line.startswith("#"):
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    return ""


def _write_env(api_key: str) -> None:
    """Write the .env file with the given API key, restricting permissions."""
    ENV_FILE.write_text(f"AISK_API_KEY={api_key}\n")
    # The .env holds a secret — keep it readable only by the owner.
    try:
        os.chmod(ENV_FILE, 0o600)
    except OSError:
        pass


def _write_conf(endpoint: str) -> None:
    """Write conf.toml with the given endpoint and default aliases."""
    CONFIG_FILE.write_text(_render_default_conf(endpoint))


def _readline_safe_prompt(prompt: str) -> str:
    """Protect ANSI escape sequences in input() prompts when readline is loaded."""
    if "readline" not in sys.modules:
        return prompt
    return _ANSI_SGR_RE.sub(lambda match: f"\x01{match.group(0)}\x02", prompt)


def interactive_init(
    input_fn=None,
    print_fn=None,
    *,
    auto: bool = False,
) -> None:
    """Interactive setup wizard for ~/.aisk/ configuration.

    Args:
        input_fn: Callable for user input (default: builtins.input).
        print_fn: Callable for output (default: builtins.print).
        auto: When True (called from ensure_config), skip overwrite prompts
              and only ask for what's missing.
    """
    if input_fn is None:
        input_fn = lambda prompt="": input(_readline_safe_prompt(prompt))
    if print_fn is None:
        print_fn = print

    # ANSI styling
    _B = "\033[38;5;33m"   # blue
    _C = "\033[36m"         # cyan
    _G = "\033[32m"         # green
    _D = "\033[2m"          # dim
    _BD = "\033[1m"         # bold
    _Y = "\033[33m"         # yellow
    _R = "\033[0m"          # reset
    _SEP = f"{_B}{'─' * 60}{_R}"

    print_fn("")
    print_fn(_SEP)
    print_fn(f"  {_BD}aisk{_R} {_D}— setup{_R}")
    print_fn(_SEP)

    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    # --- conf.toml ---
    print_fn(f"\n  {_C}{_BD}Endpoint{_R}")
    print_fn(f"  {_D}OpenRouter by default — any OpenAI-compatible endpoint works{_R}")

    if CONFIG_FILE.exists():
        if auto:
            print_fn(f"  {_D}conf.toml exists — kept{_R}")
        else:
            print_fn(f"  {_D}conf.toml already exists at {CONFIG_FILE}{_R}")
            overwrite = input_fn(f"  {_Y}Overwrite? [y/N]{_R} ").strip().lower()
            if overwrite in ("y", "yes"):
                endpoint = input_fn(
                    f"  Endpoint [{_D}{DEFAULT_ENDPOINT}{_R}]: "
                ).strip()
                if not endpoint:
                    endpoint = DEFAULT_ENDPOINT
                _write_conf(endpoint)
                print_fn(f"  {_G}✓{_R} Wrote {_D}{CONFIG_FILE}{_R}")
            else:
                print_fn(f"  {_D}skipped{_R}")
    else:
        endpoint = input_fn(
            f"  URL [{_D}{DEFAULT_ENDPOINT}{_R}]: "
        ).strip()
        if not endpoint:
            endpoint = DEFAULT_ENDPOINT
        _write_conf(endpoint)
        print_fn(f"  {_G}✓{_R} {endpoint}")

    # --- .env ---
    print_fn(f"\n  {_C}{_BD}API Key{_R}")

    existing_key = _read_existing_key()
    if existing_key:
        if auto:
            print_fn(f"  {_D}key exists — kept{_R}")
        else:
            print_fn(f"  {_D}current: {_mask_key(existing_key)}{_R}")
            overwrite = input_fn(f"  {_Y}Overwrite? [y/N]{_R} ").strip().lower()
            if overwrite in ("y", "yes"):
                new_key = input_fn(f"  AISK_API_KEY: ").strip()
                if new_key:
                    _write_env(new_key)
                    print_fn(f"  {_G}✓{_R} updated")
                else:
                    print_fn(f"  {_D}empty — kept existing{_R}")
            else:
                print_fn(f"  {_D}skipped{_R}")
    else:
        new_key = input_fn(f"  AISK_API_KEY: ").strip()
        if new_key:
            _write_env(new_key)
            print_fn(f"  {_G}✓{_R} saved")
        else:
            _write_env("")
            print_fn(f"  {_Y}!{_R} empty — edit {_D}~/.aisk/.env{_R} later")

    print_fn("")
    print_fn(_SEP)
    print_fn(f"  {_G}✓{_R} Config saved to {_BD}~/.aisk/{_R}")
    print_fn(_SEP)
    print_fn("")
